### ISSUE TITLE
[Mod] Apple Core issue

### ISSUE THREAD

**Issue by braddevans** [CrucibleMC/Grimoire-Mixins-1.7.10#3]
`mod version`: AppleCore-mc1.7.10-3.0.0
`desc`: mod stops server from loading and is a required coremod by several mods

[2020-03-08-1.log](https://github.com/CrucibleMC/Grimoire-Mixins/files/4303854/2020-03-08-1.log)

**Comment by EverNife** [comment]
Try adding `-noverify` on your JVM arguments ant test it.

**Comment by braddevans** [comment]
ok that worked
thanks


could you add that to the readme.md as some troubleshooting `args`
