### ISSUE TITLE
Preciso de uma ajuda

### ISSUE THREAD

**Issue by EduBRz** [CrucibleMC/Grimoire-Mixins-1.7.10#4]
Olá meu colegas dev , gostaria de saber qual nick fake de trust  exemplo: Botania ,EnderIO , etc pois com autotrust funciona apenas alguns minutos e para

**Comment by EverNife** [comment]
Hmm, temos um grupo do discord, sua pergunta está muito fora do escopo desse projeto.

Envia a pergunta lá no discord do CrucibleMC que a gente auxilia :D

https://discord.gg/jWSTJ4d
