### ISSUE TITLE
License Request

### ISSUE THREAD

**Issue by mitchej123** [CrucibleMC/Grimoire-Mixins-1.7.10#5]
Hey, I noticed that Grimore itself is open sourced license, but the mixins don't have a license list.  I'd love to adapt some of them for https://github.com/GTNewHorizons/hodgepodge and was wondering if you'd be willing to put them under MIT/GPL/LGPL?  (Also feel free to adapt any from hodgepodge)

Thanks!

**Comment by EverNife** [comment]
Added at 9fe82763fcfaa9c2ab10c4fd61538ff813b7fe9d

**Comment by mitchej123** [comment]
Thanks!
