### ISSUE TITLE
Pam's Harvestcraft Interaction Issues

### ISSUE THREAD

**Issue by StoneLegion** [CrucibleMC/Grimoire-Mixins-1.7.10#7]
With Pam's and Crucible we hit a few issues via interactions.

The one big one is eating base foods tends to not work when looking at a block or the ground. It ends up eating it / desyncing the inventory, but actually not consuming / filling the food bar.

The fix to this is looking into the sky.

Another issue we hit was reported by one of our users something about clicking the fruit off tree's might been with a torch that acts up. This one I have not tested out, but I thought I throw it out incase it's a known interaction issue.

**Comment by juanmuscaria** [comment]
Open an issue with all information you have about those bugs on https://github.com/CrucibleMC/Crucible/issues
